debug: false
databaseType: yaml
users:
- username: user # Username
  password: "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=" # Hashed password from ./kvdb -generate=password
  hosts:
  - "::1"
  - 127.0.0.1
  permissionsset:
  - namespaces:
    - "*"
    permissions:
      read: true
      write: true
      list: true
- username: test # Username
  password: "n3NeDfmh3ccCvwoae4MDP59xU6AMKd6CztrcmVcomwU=" # Hashed password from ./kvdb -generate=testpassword
  hosts:
  - 172.17.0.6
  permissionsset:
  - namespaces:
    - "hello"
    permissions:
      read: true
      write: true
      list: true
  - namespaces:
    - "world"
    permissions:
      read: true
      write: false
      list: false
trustedProxies: # List of hosts that are trusted reading HostHeadders for. If request not from list only ip origin will be used
- 172.17.0.1
redis:
  address: "127.0.0.1:6379"
  # envVariableName: # Set if different from KVDB_REDIS_PASSWORD
mysql:
  address: "127.0.0.1:3306"
  # username: "kvdb"
  # databaseName: "kvdb"
  # tableName: "kvdb"
  # envVariableName: # Set if different from KVDB_MYSQL_PASSWORD
prometheus:
  enabled: true # enable /system/metrics prometheus endpoint (for all users and hosts)
  # endpoint: # Set if different from metrics

# mtls:
  # enabled: false # Enable mTLS port
  # port: 8443 # Port to use for mTLS
  # certificate: server.crt # Server certificate
  # key: server.key # Server Certificate key 
  # caCertificate: ca.crt # Server certificate chain
  # externalMTLS: false # Do not use internal certificate signing but expect external proxy
  # permissions: # permissions for mtls port
    # read: true
    # write: false
    # list: true
